# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e864a820c57cebbeeee40e316dc35b3f2c9560f59ab4feea99d7efb92394316a8bad456c2ab54fd3304ca29067ee430b1cf1e63a795ce95e5ae378724f13685

test:
  secret_key_base: a750da159aa0b702ffc8213307cf1efcf6d132a355fe2f4a6d247b9bb38b685638a16501eeea2c056800d128396e4be5ad2e9e85e3aac693afdfa5ae92b431f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
